name: aggiorna dati agenas test

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '30 21 */1 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile di miller e scrape, installa dateutils
      run: |-
        sudo apt-get install dateutils
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cp bin/scrape ~/bin
        cd ~/bin
        chmod +x mlr
        chmod +x scrape
    - name: scarica i dati
      run: |-
        export PATH=$PATH:~/bin
        export PATH=$PATH:~/.local/bin
        cd ./webservices/agenas/
        chmod +x ./agenas_date.sh
        ./agenas_date.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Data e ora aggiornamento: ${timestamp}" || exit 0
        git push
